# Generated by Django 5.0.7 on 2024-07-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_gate',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_gate',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
