# Generated by Django 5.0.7 on 2024-07-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
    ]
