# Generated by Django 5.0.7 on 2024-07-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
